version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bookManagementApiAWSLambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ozktphv6tiak" # bucket has to be previously created ??
s3_prefix = "bookManagementApiAWSLambda"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
